version: "3.8"

services:
  pgadmin:
    container_name: pgadmin4_container_intelimetrica
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgres_postgis
  postgres_postgis:
    build:
      context: ./db
      dockerfile: Dockerfile-db
    container_name: postgis
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: intelimetrica
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    command:
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - postgres_postgis